

services:
  nginx:
    build:
      dockerfile: Dockerfile
    volumes:
      - D:/newtaskhelper/Help_task_manager:/usr/share/nginx/html  # Link to Laravel's public directory
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Nginx configuration
    ports:
      - "8081:8081"  # HTTP
      - "8443:8443"  # HTTPS
    depends_on:
      - php
      - mysql
    networks:
      - web

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - D:/newtaskhelper/Help_task_manager:/usr/share/nginx/html  # Link to Laravel's public directory
    depends_on:
      - mysql
  
    networks:
      - web

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"  # Expose MySQL port to the host
    networks:
      - web

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql  # Name of the MySQL container from docker-compose
      PMA_PORT: 3306
      PMA_USER: laravel_user  # MySQL username
      PMA_PASSWORD: laravel_password  # MySQL password
    ports:
      - "8080:80"  # Expose phpMyAdmin on port 8080
    depends_on:
      - mysql
    networks:
      - web

networks:
  web:

volumes:
  db_data:
